"use client";
import Layout from '../components/Layout';
import './globals.css';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout remains a server component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}